pybo/views/answer_views.py
from datetime import datetime

from flask import Blueprint, url_for, request, render_template, g, flash
from werkzeug.utils import redirect

from pybo import db
from pybo.forms import AnswerForm
from pybo.models import Question, Answer
from .auth_views import login_required

bp = Blueprint('answer', __name__, url_prefix='/answer')

'''
create 함수의 매개변수 question_id는 URL 매핑 규칙을 통해 전달된다.
methods : 'POST'로 설정, 답변을 저장하는 질문 상세 템플릿의 form 속성이 POST 방식으로 같은 값을 지정해야 한다.
- 다른 폼 방식을 지정하면 'Method Not Allowed' 에러가 발생한다.
'''
# 답변 등록 라우팅 함수 수정하기
# POST 요청만 있으므로 분기처리 불필요
@bp.route('/create/<int:question_id>', methods=('POST',))
@login_required
def create(question_id):
    form = AnswerForm()
    question = Question.query.get_or_404(question_id)
    if form.validate_on_submit():
        content = request.form['content']
        answer = Answer(content=content, create_date=datetime.now(), user=g.user)
        question.answer_set.append(answer)
        db.session.commit()
        return redirect('{}#answer_{}'.format(
            url_for('question.detail', question_id=question_id), answer.id))
    return render_template('question/question_detail.html', question=question, form=form)

# 2025-08-05, 답변 수정 기능 구현
@bp.route('/modify/<int:answer_id>/', methods=('GET', 'POST'))
@login_required
def modify(answer_id):
    answer = Answer.query.get_or_404(answer_id)
    if g.user != answer.user:
        flash('수정 권한이 없습니다.')
        return redirect(url_for('question.detail', question_id=answer.question.id))
    if request.method == 'POST':
        form = AnswerForm()
        if form.validate_on_submit():
            form.populate_obj(answer)
            answer.modify_date = datetime.now() # 수정 날짜 업데이트
            db.session.commit()
            return redirect('{}#answer_{}'.format(
                url_for('question.detail', question_id=answer.question.id), answer.id))
    else: # GET 요청인 경우
        form = AnswerForm(obj=answer)
    return render_template('answer/answer_form.html', form=form)

# 2025-08-05, 답변 삭제 기능 구현
@bp.route('/delete/<int:answer_id>/', methods=('POST',))
@login_required
def delete(answer_id):
    answer = Answer.query.get_or_404(answer_id)
    question_id = answer.question.id
    if g.user != answer.user:
        flash('삭제 권한이 없습니다.')
    else:
        db.session.delete(answer)
        db.session.commit()
    return redirect(url_for('question.detail', question_id=question_id))

# 2025-08-05, 답변 추천 기능 구현
@bp.route('/vote/<int:answer_id>/')
@login_required
def vote(answer_id):
    _answer = Answer.query.get_or_404(answer_id)
    if g.user == _answer.user:
        flash('자신의 답변에 추천할 수 없습니다.')
    else:
        _answer.voter.append(g.user)
        db.session.commit()
    return redirect('{}#answer_{}'.format(url_for('question.detail', question_id=_answer.question.id), _answer.id))

pybo/views/comment_views.py
from datetime import datetime

from flask import Blueprint, url_for, request, render_template, g, flash
from werkzeug.utils import redirect

from .. import db
from pybo.forms import CommentForm
from pybo.models import Question, Answer, Comment
from .auth_views import login_required

bp = Blueprint('comment', __name__, url_prefix='/comment')

@bp.route('/create/question/<int:question_id>/', methods=('POST',))
@login_required
def create_question_comment(question_id):
    form = CommentForm()
    question = Question.query.get_or_404(question_id)
    if form.validate_on_submit():
        comment = Comment(content=form.content.data, create_date=datetime.now(), user=g.user, question=question)
        db.session.add(comment)
        db.session.commit()
    else:
        for field, errors in form.errors.items():
            for error in errors:
                flash(error)
    return redirect(url_for('question.detail', question_id=question_id))

@bp.route('/create/answer/<int:answer_id>/', methods=('POST',))
@login_required
def create_answer_comment(answer_id):
    form = CommentForm()
    answer = Answer.query.get_or_404(answer_id)
    if form.validate_on_submit():
        comment = Comment(content=form.content.data, create_date=datetime.now(), user=g.user, answer=answer)
        db.session.add(comment)
        db.session.commit()
    else:
        for field, errors in form.errors.items():
            for error in errors:
                flash(error)
    return redirect(url_for('question.detail', question_id=answer.question.id))

@bp.route('/modify/<int:comment_id>/', methods=('GET', 'POST'))
@login_required
def modify(comment_id):
    comment = Comment.query.get_or_404(comment_id)
    if g.user != comment.user:
        flash('수정 권한이 없습니다.')
        return redirect(_redirect_target(comment))
    if request.method == 'POST':
        form = CommentForm()
        if form.validate_on_submit():
            comment.content = form.content.data
            comment.modify_date = datetime.now()
            db.session.commit()
            return redirect(_redirect_target(comment))
    else:
        form = CommentForm(obj=comment)
    return render_template('comment/comment_form.html', form=form)

@bp.route('/delete/<int:comment_id>/', methods=('POST',))
@login_required
def delete(comment_id):
    comment = Comment.query.get_or_404(comment_id)
    if g.user != comment.user:
        flash('삭제 권한이 없습니다.')
    else:
        db.session.delete(comment)
        db.session.commit()
    return redirect(_redirect_target(comment))


def _redirect_target(comment):
    if comment.question_id:
        return url_for('question.detail', question_id=comment.question_id)
    else:
        return url_for('question.detail', question_id=comment.answer.question.id)

pybo/views/question_views.py
from datetime import datetime

from flask import Blueprint, render_template, request, url_for, g, flash
from werkzeug.utils import redirect
from sqlalchemy import func

from .. import db
from pybo.models import Question, Answer, User
from pybo.forms import QuestionForm, AnswerForm, CommentForm
from pybo.views.auth_views import login_required

bp = Blueprint('question', __name__, url_prefix='/question')

@bp.route('/list/')
def _list():
    page = request.args.get('page', type=int, default=1)
    kw = request.args.get('kw', type=str, default='')
    question_list = Question.query.order_by(Question.create_date.desc())
    if kw:  # 검색어가 있는 경우
        search = '%%{}%%'.format(kw)
        sub_query = db.session.query(Answer.question_id, Answer.content, User.username).join(User, Answer.user_id == User.id).subquery()
        question_list = question_list.join(User).outerjoin(sub_query, sub_query.c.question_id == Question.id) \
                         .filter(Question.subject.ilike(search) |
                                 Question.content.ilike(search) |
                                 User.username.ilike(search) |
                                 sub_query.c.content.ilike(search) |
                                 sub_query.c.username.ilike(search)
                                 ).distinct()  # 중복된 질문을 제거하기 위해 distinct() 사용
    question_list = question_list.paginate(page=page, per_page=10)
    return render_template('question/question_list.html', question_list=question_list, kw=kw, page=page)

@bp.route('/detail/<int:question_id>/')
def detail(question_id):
    # URL에서 question_id를 정수형으로 가져오고, 페이지 번호와 정렬 방식도 가져옴
    # request.args.get() : 쿼리 문자열에서 값을 가져오는 함수
    page = request.args.get('page', type=int, default=1)
    sort = request.args.get('sort', type=str, default='recent')
    question = Question.query.get_or_404(question_id)

    # [조회수 기능] 조회 수 증가 (view_count가 None인 경우 0으로 초기화)
    if question.view_count is None:
        question.view_count = 1
    else:
        question.view_count += 1
    db.session.commit()

    form = AnswerForm()  # 답변 폼 생성
    comment_form = CommentForm()  # 댓글 폼 생성
    # build answers query with sorting
    answers_query = Answer.query.filter(Answer.question_id == question_id)
    # 게시글 내 정렬 방식에 따른 답변 정렬
    if sort == 'recommend': # 추천순
        answers_query = answers_query.outerjoin(Answer.voter).group_by(Answer.id).order_by(func.count(User.id).desc(), Answer.create_date.desc())
    else: # 최신순
        answers_query = answers_query.order_by(Answer.create_date.desc())
    answers = answers_query.paginate(page=page, per_page=10)
    return render_template('question/question_detail.html', question=question, form=form, answers=answers, comment_form=comment_form, sort=sort, page=page)

'''
2025-07-25, 질문 등록 기능 구현
- request.method : creat 함수로 요청된 전송 방식
- form.validate_on_submit() : 전송된 폼 데이터의 정합성을 점검
    QuestionForm 클래스의 각 속성에 지정한 DataRequired() 같은 점검 항목에 이상이 없는지 확인
    
2025-08-05, 로그인 필요 함수 @login_required 데코레이터 추가
- 로그인하지 않은 사용자가 질문 등록을 시도하면 로그인 페이지로 리다이렉트.
- @login_required 데코레이터는 @bp.route 데코레이터보다 위에 위치할 경우 동작하지 않음
'''

# 데이터 전송 방식이 POST 인지 GET인지에 따라서 다르게 처리하는 부분이 코드의 핵심
@bp.route('/create/', methods=['GET', 'POST'])
@login_required
def create():
    form = QuestionForm()
    if request.method == 'POST' and form.validate_on_submit():
        question = Question(subject=form.subject.data, content=form.content.data, create_date=datetime.now(), user=g.user)
        db.session.add(question)
        db.session.commit()
        return redirect(url_for('main.index')) # 질문 목록 페이지로 리다이렉트
    return render_template('question/question_form.html', form=form)

# 2025-08-05, 질문 수정 기능 구현
# - 질문 수정은 질문 작성자만 가능하도록 구현
# - 질문 작성자가 아닌 사용자가 수정하려고 하면 '수정 권한이 없습니다.' 메시지를 출력하고 질문 상세 페이지로 리다이렉트
# - 질문 작성자가 수정하려고 하면 질문 폼에 기존 질문 데이터를 채워 넣어 수정할 수 있도록 함
@bp.route('/modify/<int:question_id>/', methods=['GET', 'POST'])
@login_required
def modify(question_id):
    question = Question.query.get_or_404(question_id)
    if g.user != question.user:
        flash('수정 권한이 없습니다.')
        return redirect(url_for('question.detail', question_id=question_id))
    if request.method == 'POST': # POST 요청인 경우
        form = QuestionForm()
        if form.validate_on_submit():
            form.populate_obj(question)
            question.modify_date = datetime.now()
            db.session.commit()
            return redirect(url_for('question.detail', question_id=question_id))
    else:   # GET 요청인 경우
        form = QuestionForm(obj=question) # 기존 질문 데이터를 폼에 채워 넣음
    return render_template('question/question_form.html', form=form)

# 2025-08-05, 질문 삭제 기능 구현
@bp.route('/delete/<int:question_id>')
@login_required
def delete(question_id):
    question = Question.query.get_or_404(question_id)

    if g.user != question.user:
        flash('삭제 권한이 없습니다.')
        return redirect(url_for('question.detail', question_id=question_id))
    db.session.delete(question)
    db.session.commit()
    return redirect(url_for('question._list'))  # 질문 목록 페이지로 리다이렉트

# 2025-08-07, 질문 추천 기능 구현
@bp.route('/vote/<int:question_id>')
@login_required
def vote(question_id):
    _question = Question.query.get_or_404(question_id)
    if g.user == _question.user:
        flash('자신의 질문에 추천할 수 없습니다.')
    else:
        _question.voter.append(g.user)
        db.session.commit()
    return redirect(url_for('question.detail', question_id=question_id))

pybo/templates/question/question_detail.html
{% extends 'base.html' %}
{% block content %}
<link rel="stylesheet" href="{{ url_for('static', filename='bootstrap.min.css') }}">
<div class="container my-3">
    <!-- flash 오류 -->
    {%  for message in get_flashed_messages() %}
    <div class="alert alert-danger" role="alert">
        {{ message }}
    </div>
    {% endfor %}
    <!-- 질문 -->
    <!-- 제목 -->
    <h2 class="border-bottom py-2">{{ question.subject }}</h2>
    <div class="card my-3">
        <div class="card-body">
            <div class="card-text" style="white-space: pre-line;">{{ question.content }}</div>
            <div class="d-flex justify-content-end">
                {% if question.modify_date %}
                    <div class="badge bg-light text-dark p-2 text-start mx-3">
                        <div class="mb-2">modified at</div>
                        <div>{{ question.modify_date|datetime }}</div>
                    </div>
                {% endif %}
                <div class="badge bg-light text-dark p-2 text-start">
                    <div class="mb-2">{{ question.user.username }}</div>
                    <div>{{ question.create_date|datetime }}</div>
                </div>
            </div>
            <div class="my-3">
                <a href="javascript:void(0)" data-uri="{{ url_for('question.vote', question_id=question.id) }}"
                   class="recommend btn btn-sm btn-outline-secondary"> 추천
                    <span class="badge rounded-pill bg-success">{{ question.voter|length }}</span>
                </a>
                <span class="text-muted ms-3">
                    <i class="fas fa-eye"></i> 조회 {{ question.view_count or 0 }}
                </span>
                {% if g.user == question.user %}
                <a href="{{ url_for('question.modify', question_id=question.id) }}"
                   class="btn btn-sm btn-outline-secondary">수정</a>
                <a href="javascript:void(0)" class="delete btn btn-sm btn-outline-secondary"
                   data-uri="{{ url_for('question.delete', question_id=question.id) }}">삭제</a>
                {% endif %}
            </div>
        </div>
        <div class="my-action-buttons">
            <a href="#" class="my-action" onclick="toggleCommentForm('question-{{ question.id }}'); return false;">
                <i class="fas fa-comment"></i>댓글
            </a>
            <a href="javascript:void(0)" data-uri="{{ url_for('question.vote', question_id=question.id) }}" class="recommend my-action">
                <i class="fas fa-thumbs-up"></i>추천 ({{ question.voter|length }})
            </a>
        </div>
        <!-- 질문 댓글 -->
        {% if question.comment_set %}
            <div class="comment-block">
                <div class="mt-2">
                    {% for comment in question.comment_set %}
                    <div class="comment py-2 text-muted">
                        <span style="white-space: pre-line;">{{ comment.content }}</span>
                        <span>
                            - <a href="#" class="text-muted">{{ comment.user.username }}</a>,
                            <i class="fas fa-clock ml-1"></i>{{ comment.create_date|datetime }}
                            {% if comment.modify_date %}
                            (수정:{{ comment.modify_date|datetime }})
                            {% endif %}
                        </span>
                        {% if g.user == comment.user %}
                        <a href="{{ url_for('comment.modify', comment_id=comment.id) }}" class="small">수정</a>,
                        <a href="#" class="small delete" data-uri="{{ url_for('comment.delete', comment_id=comment.id) }}">삭제</a>
                        {% endif %}
                    </div>
                    {% endfor %}
                </div>
            </div>
        {% endif %}
        <div id="question-{{ question.id }}" class="comment-form my-3" style="display: none;">
            {% if g.user %}
            <form action="{{ url_for('comment.create_question_comment', question_id=question.id) }}" method="post" class="my-3">
                {{ comment_form.csrf_token }}
                <div class="mb-3">
                    <textarea name="content" class="form-control" rows="2" placeholder="댓글을 입력하세요"></textarea>
                </div>
                <input type="submit" value="댓글등록" class="btn btn-primary btn-sm">
            </form>
            {% else %}
            <div class="alert alert-warning">
                댓글을 작성하려면 <a href="{{ url_for('auth.login') }}">로그인</a>이 필요합니다.
            </div>
            {% endif %}
        </div>
    </div>
    <!-- 답변 목록 -->
    <div class="d-flex justify-content-between align-items-center my-3">
        <h5 class="border-bottom py-2">{{ answers.total }}개의 답변이 있습니다.</h5>
        <div class="btn-group">
            <a href="{{ url_for('question.detail', question_id=question.id, sort='recent') }}" class="{% if sort=='recent' %}fw-bold{% endif %}">
                <i class="fas fa-thumbs-up"></i>최신순
            </a>
            <a href="{{ url_for('question.detail', question_id=question.id, sort='recommend') }}" class="{% if sort=='recommend' %}fw-bold{% endif %}">
                <i class="fas fa-list"></i>추천순
            </a>
        </div>
    </div>
    {% for answer in answers.items %}
    <a id="answer_{{ answer.id }}"></a>
    <div class="card my-3">
        <div class="card-body">
            <div class="card-text" style="white-space: pre-line;">{{ answer.content }}</div>
            <div class="d-flex justify-content-end">
                {% if answer.modify_date %}
                    <div class="badge bg-light text-dark p-2 text-start mx-3">
                        <div class="mb-2">modified at</div>
                        <div>{{ answer.modify_date|datetime }}</div>
                    </div>
                {% endif %}
                <div class="badge bg-light text-dark p-2 text-start">
                    <div class="mb-2">{{ answer.user.username }}</div>
                    <div>{{ answer.create_date|datetime }}</div>
                </div>
            </div>
        </div>
        <!-- 답변 댓글 -->
        {% if answer.comment_set %}
            <div class="mt-3">
                {% for comment in answer.comment_set %}
                <div class="comment py-2 text-muted">
                    <span style="white-space: pre-line;">{{ comment.content }}</span>
                    <span>
                        - <a href="#" class="text-muted">{{ comment.user.username }}</a>, {{ comment.create_date|datetime }}
                        {% if comment.modify_date %}
                        (수정:{{ comment.modify_date|datetime }})
                        {% endif %}
                    </span>
                    {% if g.user == comment.user %}
                    <a href="{{ url_for('comment.modify', comment_id=comment.id) }}" class="small">수정</a>,
                    <a href="#" class="small delete" data-uri="{{ url_for('comment.delete', comment_id=comment.id) }}">삭제</a>
                    {% endif %}
                </div>
                {% endfor %}
            </div>
        {% endif %}
        <!--  -->
        <div class="my-action-buttons">
            <a href="#" class="my-action" onclick="toggleCommentForm('answer-{{ answer.id }}'); return false;">
                <i class="fas fa-comment"></i>댓글
            </a>
            <a href="javascript:void(0)" data-uri="{{ url_for('question.vote', question_id=question.id) }}" class="recommend my-action">
                <i class="fas fa-thumbs-up"></i>추천 ({{ question.voter|length }})
            </a>
            {% if g.user == answer.user %}
                <a href="{{ url_for('answer.modify', answer_id=answer.id) }}"
                   class="btn btn-sm btn-outline-secondary">수정</a>
                <a href="#" class="delete btn btn-sm btn-outline-secondary "
                   data-uri="{{ url_for('answer.delete', answer_id=answer.id) }}">삭제</a>
                {% endif %}
        </div>
        <div id="answer-{{ answer.id }}" class="comment-form my-3" style="display: none;">
            {% if g.user %}
                <form action="{{ url_for('comment.create_answer_comment', answer_id=answer.id) }}" method="post" class="my-3">
                    {{ comment_form.csrf_token }}
                    <div class="mb-3">
                        <textarea name="content" class="form-control" rows="2" placeholder="댓글을 입력하세요"></textarea>
                    </div>
                    <input type="submit" value="댓글등록" class="btn btn-primary btn-sm">
                </form>
            {% else %}
            <div class="alert alert-warning">
                댓글을 작성하려면 <a href="{{ url_for('auth.login') }}">로그인</a>이 필요합니다.
            </div>
            {% endif %}
        </div>
    </div>
    {% endfor %}
    <!-- 답변 페이지네이션 -->
    <ul class="pagination justify-content-center">
        {% if answers.has_prev %}
        <li class="page-item">
            <a class="page-link" href="{{ url_for('question.detail', question_id=question.id, page=answers.prev_num, sort=sort) }}">이전</a>
        </li>
        {% endif %}
        {% for p in answers.iter_pages(left_edge=1, right_edge=1, left_current=2, right_current=2) %}
            {% if p %}
            <li class="page-item {% if p == answers.page %}active{% endif %}">
                <a class="page-link" href="{{ url_for('question.detail', question_id=question.id, page=p, sort=sort) }}">{{ p }}</a>
            </li>
            {% else %}
            <li class="page-item disabled"><span class="page-link">…</span></li>
            {% endif %}
        {% endfor %}
        {% if answers.has_next %}
        <li class="page-item">
            <a class="page-link" href="{{ url_for('question.detail', question_id=question.id, page=answers.next_num, sort=sort) }}">다음</a>
        </li>
        {% endif %}
    </ul>
    <!-- 답변 등록 -->
    <form action="{{ url_for('answer.create', question_id=question.id) }}" method="post" class="my-3">
        {{ form.csrf_token }}
        <!-- 오류표시 Start -->
        {% if form.errors %}
        <div class="alert alert-danger" role="alert">
            {% for field, errors in form.errors.items() %}
            <strong>{{ form[field].label }}</strong>
            <ul>
                {% for error in errors %}
                <li>{{ error }}</li>
                {% endfor %}
            </ul>
            {% endfor %}
        </div>
        {% endif %}
        <!-- 오류표시 End -->
        <div class="mb-3">
            <textarea {% if not g.user %}disabled{% endif %} name="content" id="answer-content" class="form-control" rows="10"></textarea>
        </div>
        <input type="submit" value="답변등록" class="btn btn-primary">
    </form>
</div>
{% endblock %}
{% block script %}
<script type='text/javascript'>
    const delete_elements = document.getElementsByClassName("delete");
    Array.from(delete_elements).forEach(function(element) {
        element.addEventListener('click', function() {
            if(confirm("정말로 삭제하시겠습니까?")) {
                location.href = this.dataset.uri;
            };
        });
    });

    const recommend_elements = document.getElementsByClassName("recommend");
    Array.from(recommend_elements).forEach(function(element) {
        element.addEventListener('click', function() {
            if(confirm("정말로 추천하시겠습니까?")) {
                location.href = this.dataset.uri;
            };
        });
    });
    // 댓글 폼 토글 함수
    function toggleCommentForm(id) {
        const form = document.getElementById(id);
        if (form.style.display === "none" || form.style.display === "") {
            form.style.display = "block";
        } else {
            form.style.display = "none";
        }
    }

    // 답변 등록 폼에 SimpleMDE 마크다운 에디터 적용
    {% if g.user %}
    var answerMDE = new SimpleMDE({
        element: document.getElementById("answer-content"),
        placeholder: "답변을 마크다운으로 작성하세요...",
        spellChecker: false,
        renderingConfig: {
            singleLineBreaks: false,
        },
        toolbar: ["bold", "italic", "heading", "|", "quote", "unordered-list", "ordered-list", "|", "link", "image", "|", "preview", "side-by-side", "fullscreen", "|", "guide"]
    });
    {% endif %}
</script>
{% endblock %}

pybo/templates/question/question_list.html
{% extends 'base.html' %}
{% block content %}
<div class="container my-3">
    <div class="row my-3">
        <div class="col-6">
            <a href="{{ url_for('question.create') }}" class="btn btn-primary">질문 등록하기</a>
        </div>
        <div class="col-6">
            <div class="input-group">
                <!-- js에서 텍스트창에 입력된 값을 얻기 위한 id 속성 추가, 2025-08-07 jylee -->
                <input type="text" id="search_kw" class="form-control" value="{{ kw or '' }}">
                <div class="input-group-append">
                    <button class="btn btn-outline-secondary" type="button" id="btn_search">찾기</button>
                </div>
            </div>
        </div>
    </div>
    <table class="table">
        <thead>
        <tr class="text-center table-dark">
            <th>번호</th>
            <th style="width:50%">제목</th>
            <th>글쓴이</th>
            <th>작성일시</th>
            <th>조회</th>
        </tr>
        </thead>
        <tbody>
        {% if question_list %}
        {% for question in question_list.items %}
        <tr class="text-center">
            <td>{{ question_list.total - ((question_list.page-1) * question_list.per_page) - loop.index0 }}</td>
            <td class="text-start">
                <a href="{{ url_for('question.detail', question_id=question.id) }}">{{ question.subject }}</a>
                {% if question.answer_set|length > 0 %}
                <span class="text-danger small mx-2">{{ question.answer_set|length }}</span>
                {% endif %}
            </td>
            <td>{{ question.user.username }}</td>
            <td>{{ question.create_date|datetime }}</td>
            <td>{{ question.view_count or 0 }}</td>
        </tr>
        {% endfor %}
        {% else %}
        <tr>
            <td colspan="3">질문이 없습니다.</td>
        </tr>
        {% endif %}
        </tbody>
    </table>
    <!-- 페이징처리 시작 -->
    <ul class="pagination justify-content-center">
        <!-- 이전페이지 -->
        {% if question_list.has_prev %}
        <li class="page-item">
            <a class="page-link" data-page="{{ question_list.prev_num }}" href="javascript:void(0)">이전</a>
        </li>
        {% else %}
        <li class="page-item disabled">
            <a class="page-link" tabindex="-1" aria-disabled="true" href="javascript:void(0)">이전</a>
        </li>
        {% endif %}
        <!-- 페이지번호 -->
        {% for page_num in question_list.iter_pages() %}
        {% if page_num %}
        {% if page_num != question_list.page %}
        <li class="page-item">
            <a class="page-link" data-page="{{ page_num }}" href="javascript:void(0)">{{ page_num }}</a>
        </li>
        {% else %}
        <li class="page-item active" aria-current="page">
            <a class="page-link" href="javascript:void(0)">{{ page_num }}</a>
        </li>
        {% endif %}
        {% else %}
        <li class="disabled">
            <a class="page-link" href="javascript:void(0)">...</a>
        </li>
        {% endif %}
        {% endfor %}
        <!-- 다음페이지 -->
        {% if question_list.has_next %}
        <li class="page-item">
            <a class="page-link" data-page="{{ question_list.next_num }}" href="javascript:void(0)">다음</a>
        </li>
        {% else %}
        <li class="page-item disabled">
            <a class="page-link" tabindex="-1" aria-disabled="true" href="javascript:void(0)">다음</a>
        </li>
        {% endif %}
    </ul>
    <!-- 페이징처리 끝 -->
    <!-- 질문 등록 버튼 : 검색창 위치로 이동, 2025-08-07 jylee -->
</div>
<!-- 검색어와 페이지 정보를 유지하기 위한 폼 : page, kw를 동시에 GET 방식으로 요청가능 -->
<form id="searchForm" method="get" action="{{ url_for('question._list') }}">
    <input type="hidden" id="kw" name="kw" value="{{ kw or '' }}">
    <input type="hidden" id="page" name="page" value="{{ page }}">
</form>
{% endblock %}
{% block script %}
<script type='text/javascript'>
    // 페이지 번호 클릭시 페이지 정보를 유지하기 위한 폼에 값을 설정하고 제출
    const page_elements = document.getElementsByClassName("page-link");
    Array.from(page_elements).forEach(function(element) {
        element.addEventListener('click', function() {
            document.getElementById('page').value = this.dataset.page;
            document.getElementById('searchForm').submit();
        });
    });
    // 검색버튼 클릭시 검색어와 페이지 정보를 유지하기 위한 폼에 값을 설정하고 제출
    const btn_search = document.getElementById("btn_search");
    btn_search.addEventListener('click', function() {
        document.getElementById('kw').value = document.getElementById('search_kw').value;
        document.getElementById('page').value = 1;  // 검색버튼을 클릭할 경우 1페이지부터 조회한다.
        document.getElementById('searchForm').submit();
    });
</script>
{% endblock %}